### ISSUE TITLE
How to do inference on our own dataset?

### ISSUE THREAD

**Issue by DongChen06** [Secilia-Cxy/SOFTS#1]
Hi authors, thanks for your insightful paper! I am wondering how to make inferences on our own dataset, can you guide me through the steps (checkpoints, fine-tuning, etc). Thanks

**Comment by Secilia-Cxy** [comment]
Thank you for your question. To make inferences on your own dataset, you can follow the steps outlined in the **Custom Datasets** section of the `README.md` file. This process involves training our model using your dataset. If you encounter any issues or need further assistance, please don't hesitate to ask.

**Comment by TDL77** [comment]
Thank you for your hard work.
Could you make an example of use in a Jupyter notebook using some kind of dataset as an example?

**Comment by Secilia-Cxy** [comment]
> Thank you for your hard work. Could you make an example of use in a Jupyter notebook using some kind of dataset as an example?

Of course! We have provided a Jupyter notebook named `run_on_your_own_dataset.ipynb`, which you can refer to for help.
