### ISSUE TITLE
Does the code really match the article ?

### ISSUE THREAD

**Issue by hamezignobouenz** [Secilia-Cxy/SOFTS#12]
Hello and thanks for making the material available !
I found that in the code the STAR modules are wrapped with some other objects (encoder and encoderlayer) which seem to use some convulution layers on top of the STAR modules. However I can't find in the paper where this happens in the displayed architecture. I'm I missing something ? Are your advertised results using the architecture in Figure 1 (I'm using the arxiv paper) or is there something else ? 

Thanks !

**Comment by hanlu-nju** [comment]
The convolution layer with kernel 1 and stride 1 is actually MLP.  The code matches the article.

**Comment by hamezignobouenz** [comment]
Hi ! Thanks a lot for taking the time to answer this one

**Comment by hanlu-nju** [comment]
You are welcome. :)
