### ISSUE TITLE
Impact of channel noise

### ISSUE THREAD

**Issue by pyuser2023** [Secilia-Cxy/SOFTS#13]
Hello, how did you add noise? Is it directly added to a channel on the entire dataset?

**Comment by Secilia-Cxy** [comment]
In each batch, we first randomly select one channel and then add noise to it.

**Comment by pyuser2023** [comment]
Thank you for your reply. Furthermore, in the ablation experiment, did you notice that channel independent MLP performed well on the ETT dataset?

**Comment by Secilia-Cxy** [comment]
Thank you for highlighting this detail. In some cases, when the correlation between different channels is low, ignoring it could potentially lead to better performance.

**Comment by pyuser2023** [comment]
Thank you for your reply. Your work has inspired me a lot.

**Comment by Secilia-Cxy** [comment]
I’m glad to hear that our work has inspired you. Please feel free to share any further thoughts or questions!
