### ISSUE TITLE
How to calculate the inference time?

### ISSUE THREAD

**Issue by trunghieuvu02** [Secilia-Cxy/SOFTS#14]
I am very interested in your work. Could you please provide the code for calculating the inference time as described in your paper? Thank you very much; I appreciate your work and assistance.

![image](https://github.com/user-attachments/assets/ae49ebe8-635d-4c33-b8db-2a0a313b4ea5)

**Comment by Secilia-Cxy** [comment]
Thank you for your kind words and interest in our work. You can find the code for calculating the training time in the file `exp/exp_long_term_forecasting.py`, specifically at line 149, where the speed calculation is performed. A similar way could be used to calculate inference time.

**Comment by trunghieuvu02** [comment]
Hi @Secilia-Cxy, Thank you for pointing that out!
