### ISSUE TITLE
Regarding Dataset Splitting

### ISSUE THREAD

**Issue by ForestsKing** [Secilia-Cxy/SOFTS#15]
The dataset splits in your paper (Table 5) directly reference Table 4 from the original iTransformer paper. However, the splitting information for the PEMS04, PEMS07, and PEMS08 datasets contains significant errors that have already been corrected in the updated iTransformer version. We hope that you will promptly correct these errors and, in future work, reinforce the verification of referenced information to ensure the quality and reliability of research outcomes.

**Comment by hanlu-nju** [comment]
Thank you for bringing this issue to our attention. We sincerely appreciate your careful review of our paper and for pointing out the mistakes in the dataset-splitting information. We will correct the mistakes soon in the following revision. Our code has been made public for a while to ensure the quality and reliability of research outcomes. If you have any further concerns or notice any other issues, please don't hesitate to let us know.
