### ISSUE TITLE
 a regression task without time stamps

### ISSUE THREAD

**Issue by Lin840591196** [Secilia-Cxy/SOFTS#19]
Hello, could you please provide an example of a regression task without time stamps?

**Comment by Secilia-Cxy** [comment]
For reference, we have already provided an example of a time series forecasting task in `run_on_your_own_dataset.ipynb`.
For datasets without timestamps, you can follow the instructions in Part 3: Prepare the dataset, specifically the guideline: "If there's no time feature, the dataset starts directly with the features."

**Comment by Lin840591196** [comment]
![image](https://github.com/user-attachments/assets/cfa388c4-8f81-4b35-a1af-34692208c77e)
Hello, thank you very much for your reply, how should I solve the error here?

**Comment by Lin840591196** [comment]
![image](https://github.com/user-attachments/assets/fae9b834-8959-4374-9714-5ad8581587a7)

**Comment by Secilia-Cxy** [comment]
> Hello, thank you very much for your reply, how should I solve the error here?

 I’m sorry for the bug, we have already fixed it. Please pull the code and try a second time.

**Comment by Lin840591196** [comment]
Thank you very much for modifying the code. Now I can run your code on the data set without timestamp.
