### ISSUE TITLE
how to use the dataset other than ETT?

### ISSUE THREAD

**Issue by Ryanssssssss** [Secilia-Cxy/SOFTS#22]
i see that in data_loader.py only have preparation for ETTh1 or m1,how can i use weather dataset or the other datasets provided by autoformer? And in the run_on_my_data.ipynb, where should put the code you provided to organize my own dataset? In the dataset_custom?

**Comment by Secilia-Cxy** [comment]
You can use the scripts provided in `scripts/long_term_forecast/`, and run them in this way: `sh scripts/long_term_forecast/Weather_script/SOFTS.sh`. In the` run_on_your_own_dataset.ipynb` notebook, you could follow the instructions outlined in Part 3, "Prepare the Dataset" to organize your own dataset accordingly.
