### ISSUE TITLE
how to add future feature

### ISSUE THREAD

**Issue by iceiceiceee** [Secilia-Cxy/SOFTS#8]
i want to add some future information as features, should i just add there features as chnnel, ignore time. 
e.g. add weather features of meteorology forecast when create weather predict model.
thank you

**Comment by hanlu-nju** [comment]
Currently, this method does not consider future covariates. However, there are possibly some ways to implement it. For example,  you can pad the focused channel to the known future and forward the padded multivariate series to the model. Although the model will forecast on all the channels, just use the prediction on the channels you are interested in.

![image](https://github.com/Secilia-Cxy/SOFTS/assets/74913048/7e4d8a50-9072-4ac7-9b9f-f1d530e9d3a5)

**Comment by 1453355014** [comment]
> Currently, this method does not consider future covariates. However, there are possibly some ways to implement it. For example, you can pad the focused channel to the known future and forward the padded multivariate series to the model. Although the model will forecast on all the channels, just use the prediction on the channels you are interested in.
> 
> ![image](https://private-user-images.githubusercontent.com/74913048/347749755-7e4d8a50-9072-4ac7-9b9f-f1d530e9d3a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDE5ODgsIm5iZiI6MTczMjYwMTY4OCwicGF0aCI6Ii83NDkxMzA0OC8zNDc3NDk3NTUtN2U0ZDhhNTAtOTA3Mi00YWM3LTliOWYtZjFkNTMwZTlkM2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMWQ1NTZmODllNmY0MDI5NjgxOWEzOGYzYWI5ZmJiZGE4NTY5Yzg3NmM3OGM0ZTg3Zjk3OTVmODEzNGEzMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O7sbwzUOaFv0eG-bNDz_iBfw74lRx6IL8cww_1XkDlw)

不是很明白，可以详细一点吗
