### ISSUE TITLE
What does the predictions contain ?

### ISSUE THREAD

**Issue by clementrx** [Secilia-Cxy/SOFTS#9]
Hi ! 

I ran the notebook and was wondering what exactly contain **predictions** ?

`predictions = Exp.predict(setting=setting, pred_data=test_data)`

We have indeed the projection of 96 and the 7 variables columns but I don't understand the dimension.

Thanks

**Comment by Secilia-Cxy** [comment]
The shape of the prediction is (11521, 96, 7), in which 11521 is the number of samples, 96 is the prediction length, and 7 is the number of channels.

**Comment by clementrx** [comment]
For example, i used `predictions_original_scale = scaler.inverse_transform(predictions[1])
predictions_df = pd.DataFrame(predictions_original_scale, columns=test_data.columns[1:]) ` to get data with original value.

Is it correct if I say that I have this datframe contains the predictions values ​​of the next 96 periods?
And in this case `predictions_original_scale = scaler.inverse_transform(predictions[2]` contains +1 period ? 

My question is how do I predict in the future in one time ?

**Comment by Secilia-Cxy** [comment]
> For example, i used `predictions_original_scale = scaler.inverse_transform(predictions[1]) predictions_df = pd.DataFrame(predictions_original_scale, columns=test_data.columns[1:]) ` to get data with original value.
> 
> Is it correct if I say that I have this datframe contains the predictions values ​​of the next 96 periods? And in this case `predictions_original_scale = scaler.inverse_transform(predictions[2]` contains +1 period ?
> 
> My question is how do I predict in the future in one time ?

Sorry for the delayed response to your question. Let me provide an example to clarify.

Assume the horizon is 96 and the lookback window is 96. For the given pred_data, we use a sliding window with a stride of 1 by default.

`prediction[0]` represents the forecast for the next 96 time points based on `pred_data[:97]`.
`prediction[1]` represents the forecast for the next 96 time points based on `pred_data[1:98]`.

Your question about predicting further into the future all at once can be addressed by using the model to generate forecasts iteratively. After predicting the initial horizon, you can use these predictions as input for the next forecast, and so on, to extend the forecast horizon.
